import os
import json
from pathlib import Path
from aptos_sdk.async_client import RestClient as _AptosClient
from aptos_sdk.account import Account
from dotenv import load_dotenv

# Load environment variables from .env automatically
load_dotenv()

class Config:
    # Flask Config
    SECRET_KEY: str = os.getenv('SECRET_KEY', '8b261a3077d88137be89194bca1465aba0ab9eee16be5f137178261b2e43f9ac')
    JWT_SECRET_KEY: str = os.getenv('JWT_SECRET_KEY', '11ae615a07681c6550376de57e2d830618dda1d15f4c2d7cf155a6b86793d554')
    JWT_ACCESS_TOKEN_EXPIRES: int = int(os.getenv('JWT_ACCESS_TOKEN_EXPIRES', '3600'))  # 1 hour
    
    # Database Config
    BASE_DIR: Path = Path(__file__).resolve().parent.parent
    SQLALCHEMY_DATABASE_URI: str = os.getenv('DATABASE_URL', 'postgresql+psycopg://forensic_user:postgres@localhost:5432/forensic_db')
    SQLALCHEMY_TRACK_MODIFICATIONS: bool = False
    
    # File Upload Config
    UPLOAD_FOLDER: str = os.path.join(BASE_DIR, 'uploads')
    ALLOWED_EXTENSIONS: set = {'pdf', 'png', 'jpg', 'jpeg', 'gif', 'txt', 'doc', 'docx'}
    MAX_CONTENT_LENGTH: int = 16 * 1024 * 1024  # 16MB
    
    # Aptos Blockchain Config (Testnet)
    APTOS_NODE_URL: str = os.getenv('APTOS_NODE_URL', 'https://fullnode.testnet.aptoslabs.com/v1')
    APTOS_FAUCET_URL: str = os.getenv('APTOS_FAUCET_URL', 'https://faucet.testnet.aptoslabs.com')
    APTOS_MODULE_ADDRESS: str = os.getenv('APTOS_MODULE_ADDRESS', '0xe57cc832da53b0676291024beae6b66174dada2234034855a9feaded1bccedab')
    APTOS_MODULE_NAME: str = os.getenv('APTOS_MODULE_NAME', 'evidence')
    APTOS_ACCOUNT_ADDRESS: str = os.getenv('APTOS_ACCOUNT_ADDRESS', '0xe57cc832da53b0676291024beae6b66174dada2234034855a9feaded1bccedab')
    # Private key should be a hex string generated by aptos-cli (no 0x prefix)
    APTOS_PRIVATE_KEY: str = os.getenv('APTOS_PRIVATE_KEY', '')
    
    @classmethod
    def init_blockchain(cls) -> object:
        """Initialize Aptos RestClient and Account. Raises if not configured."""
        try:
            # Validate configuration
            if not cls.APTOS_PRIVATE_KEY:
                raise ValueError("APTOS_PRIVATE_KEY not set. Generate via aptos-cli and set env var.")

            # Initialize async RestClient (from aptos_sdk.async_client)
            cls.REST_CLIENT = _AptosClient(cls.APTOS_NODE_URL)

            # Initialize account from private key (hex string without 0x)
            cls.APTOS_ACCOUNT = Account.load_key(cls.APTOS_PRIVATE_KEY)

            print(f"✓ Aptos client initialized at {cls.APTOS_NODE_URL}")

            # Verify publisher account matches configured address
            addr_str = str(cls.APTOS_ACCOUNT.address())  # e.g., "0x..."
            print(f"✓ Using account: {addr_str}")

            return cls.REST_CLIENT
        except Exception as e:
            if isinstance(e, (ConnectionError, FileNotFoundError, ValueError)):
                raise
            error_msg = f"CRITICAL: Aptos initialization failed: {e}"
            print(error_msg)
            raise RuntimeError(error_msg)